### ISSUE TITLE
ESM Example without a bundler

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/parquet-wasm#12]
https://rustwasm.github.io/docs/wasm-bindgen/examples/without-a-bundler.html

**Comment by disleyland** [comment]
Following the ESM approach outlined in that URL example, I am getting the following error when running the default example script:

arrow2.js:1653 Uncaught (in promise) Error: InvalidHeader
    at imports.wbg.__wbindgen_error_new (arrow2.js:1653:21)
    at arrow2_bg.wasm:0x31d954
    at arrow2_bg.wasm:0x288d2c
    at arrow2_bg.wasm:0x2e3c71
    at Object.writeParquet (arrow2.js:540:14)

My module import script is as follows:

`import init,  {
      readParquet,
      writeParquet,
      Compression,
      WriterPropertiesBuilder,
    } from 'https://unpkg.com/parquet-wasm@0.4.0-beta.5/esm/arrow2.js';

    async function run() {
        await init();
        
        // Create Arrow Table in JS
        const LENGTH = 2000;
        const rainAmounts = Float32Array.from({ length: LENGTH }, () =>
          Number((Math.random() * 20).toFixed(1))
        );
        
        const rainDates = Array.from(
          { length: LENGTH },
          (_, i) => new Date(Date.now() - 1000 * 60 * 60 * 24 * i)
        );
        
        const rainfall = tableFromArrays({
          precipitation: rainAmounts,
          date: rainDates,
        });

        const writerProperties = new WriterPropertiesBuilder()
          .setCompression(Compression.ZSTD)
          .build();
        const parquetBuffer = writeParquet(
           tableToIPC(rainfall, "stream"),
          writerProperties
        );
    }
    
    run()`

**Comment by kylebarron** [comment]
I haven't looked at this in a while but my example here uses ESM https://observablehq.com/@kylebarron/geoparquet-on-the-web

**Comment by disleyland** [comment]
yeah, the issue is with writeParquet, not readParquet.  same error when I put in the writeParquet element into that geoparquet notebook you did
