### ISSUE TITLE
Error: Unrecognized type: "LargeUtf8" (20) during parquet conversion

### ISSUE THREAD

**Issue by ddemaeyer** [kylebarron/parquet-wasm#253]
During reading of a compressed parquet file:

```{ojs}
arrow = require('apache-arrow@10.0.1')

readParquet = {
  const parquetModule = await import(
    "https://unpkg.com/parquet-wasm@0.4.0-beta.5/esm/arrow2.js"
  );
  // Need to await the default export first to initialize the WebAssembly code
  await parquetModule.default();
  return parquetModule.readParquet;
}
```
... Data loading ...

```
data = await loadData()
table = arrow.tableFromIPC(readParquet(data))
```

The error `Error: Unrecognized type: "LargeUtf8" (20)` is returned.

**Comment by ddemaeyer** [comment]
Closing since this is in the apache-arrow lib itself: see https://issues.apache.org/jira/browse/ARROW-16528

**Comment by kylebarron** [comment]
Yes indeed, this is an issue with Arrow JS. I'd love for Arrow JS to support largeutf8/largebinary/etc
