### ISSUE TITLE
Parquet files as tiles deckgl

### ISSUE THREAD

**Issue by Saumya-NebCodes** [kylebarron/parquet-wasm#261]
Do you have any guidance for creating parquet files as tiles to load them on deckgl and I want to load more than 500 million points but currently deckgl gives up after 10 million points.
The code reference https://observablehq.com/@kylebarron/geoarrow-and-geoparquet-in-deck-gl

**Comment by kylebarron** [comment]
deck.gl is limited by the size of your gpu. You're unlikely to be able to visualize 500 million points (all at once on the screen) with a standard gpu. In any case, this is off topic for this repository.
