### ISSUE TITLE
runtime error while reading large parquet

### ISSUE THREAD

**Issue by skemaikin** [kylebarron/parquet-wasm#268]
Hi!
I an currently trying to read large parquet file with ~100mln points and receiving a runtime error in wasm module. The small parquets read nicely. Is there any limtations on records count for `parquet-wasm` ?

**Comment by kylebarron** [comment]
Wasm in the browser generally has a 2GB memory limit, and the library currently has two copies, so there's certainly some limit. The easiest way around it is to read the parquet file in chunks

**Comment by skemaikin** [comment]
> Wasm in the browser generally has a 2GB memory limit, and the library currently has two copies, so there's certainly some limit. The easiest way around it is to read the parquet file in chunks

Do you mean `readParquet()` function?

In my code:
```javascript
async function parquetData() {
  const data = await fetch("http://localhost:3000/large.parquet")
  return data.arrayBuffer();
}

parquetData()
  .then((data) => {
    const parquetBytes = new Uint8Array(data);
    const decodedArrowBytes = readParquet(parquetBytes);
    ...
  })
  .catch((error) => {
      console.log('--- error\n')
      console.error(error);
  });
```
the error occures on `readParquet(parquetBytes)` call.

**Comment by kylebarron** [comment]
Yeah you're storing the whole parquet file at once and reading it at once, so it's not too surprising it runs out of memory on a large file. There are chunked apis for reading only specific chunks at a time, and you can do that as part of the fetch directly too

**Comment by skemaikin** [comment]
Thanks you for the answer! 
I'm trying to put a very large number of points (100 million is not the limit) in deck.gl using your module, and I'm trying to figure out how to do it better. I don't want to split the file into multiple parts. Could you suggest a good way to read parquet in chunks?

**Comment by kylebarron** [comment]
There's no way to read only part of a column if the file wasn't originally saved internally with multiple chunks

**Comment by skemaikin** [comment]
@kylebarron Thank you very much for your answers!
