### ISSUE TITLE
Module '"parquet-wasm/bundler/arrow2"' has no exported member '__wasm'

### ISSUE THREAD

**Issue by Maxzurek** [kylebarron/parquet-wasm#354]
I am using vite js and the 0.4.0 version of this package.

I cannot import __wasm from any of the available bundles.
When reading the java doc for the readParquetFFI function, it says the wasm memory buffer is needed when parsing the record batch:
`const WASM_MEMORY = __wasm.memory;
const recordBatch = parseRecordBatch(
    WASM_MEMORY.buffer,
    wasmArrowTable.arrayAddr(i),
    wasmArrowTable.schemaAddr(),
    true
  );`

Am I missing something?

**Comment by kylebarron** [comment]
if you use the latest alpha you can use the `wasm_memory` function (called something like that) to access the wasm memory instance. previously it was output-bundle dependent for how to access

**Comment by Maxzurek** [comment]
Thanks for the quick answer. Is the latest alpha version 0.5.0-alpha.1 from npm? If so, I can import the _memory function if that is what is needed, but now I can't import the readParquetFFI function as it is not exported from any of the bundles.

**Comment by kylebarron** [comment]
0.5.0 is now published, and the documentation is updated. You should be able to use `readParquet().toFFI()`
