### ISSUE TITLE
Update README documentation

### ISSUE THREAD

**Issue by Sheap** [kylebarron/parquet-wasm#390]
Hello,
I'm unable to replicate the example of readParquetFFI in your documentation. I'm using the default `parquet-wasm`/bundler import, and I don't see how to get the wasm memory in that mode, as it doesn't seem to export wasm directly, nor does it have a default export.
Cheers

**Comment by kylebarron** [comment]
Ah sorry I updated the docs website in the latest release but didn't refresh the README. The up to date instructions are in the docs website, e.g. here https://kylebarron.dev/parquet-wasm/functions/bundler_arrow2.readParquet.html. And you can now use https://kylebarron.dev/parquet-wasm/functions/bundler_arrow2.wasmMemory.html to access the memory.

**Comment by Sheap** [comment]
Thanks, got it working now :smile:
