### ISSUE TITLE
bundler version doesn't work in production since 0.4.0-beta.5

### ISSUE THREAD

**Issue by Sheap** [kylebarron/parquet-wasm#396]
When trying to read a parquet file in any version since 0.4.0-beta.5, I get an error that `wasm` is undefined, but only in production builds. Running on a dev server works fine.
I'm using vite, with vite-plugin-wasm and vite-plugin-top-level-await

**Comment by kylebarron** [comment]
This is probably related to an underlying wasm-bindgen upgrade. I don't think it's anything I changed myself.

**Comment by kylebarron** [comment]
This is likely to be an issue with vite and rust-wasm in general, and it doesn't seem that I'm doing anything wrong, so I'll close.
