### ISSUE TITLE
Changelog notes:

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/parquet-wasm#445]
List of breaking changes:

- Name of bundle changed from `arrow1.js` to `parquet_wasm.js` as we no longer have an arrow2 version

**Comment by matbee-eth** [comment]
I dont understand how to get this project imported. Documentation says arrow2, arrow1, etc. But I see no such thing. and `import { readParquet } from "parquet-wasm";` returns 
```
Cannot find module 'parquet-wasm' or its corresponding type declarations.ts(2307)
```

**Comment by kylebarron** [comment]
you should look at the readme for the git tag that you have installed

**Comment by kylebarron** [comment]
> I've tried copying the files directly into my project and it errors:

that's probably because you're missing the underlying rust bundle

**Comment by matbee-eth** [comment]
> > I've tried copying the files directly into my project and it errors:
> 
> that's probably because you're missing the underlying rust bundle

I'm using WASM in the browser, not rust, I'm very confused.

**Comment by kylebarron** [comment]
When I say "rust" I mean webassembly.

```
Cannot read properties of undefined (reading '__wbindgen_add_to_stack_pointer')
```
usually means either that the Wasm bundle was not loaded or, if you're using the `esm` entrypoint, that the wasm was not initialized. With the `esm` entrypoint you need to await the default export.
