### ISSUE TITLE
Cannot read properties of undefined (reading 'fromIPCStream') 

### ISSUE THREAD

**Issue by MaTiAtSIE** [kylebarron/parquet-wasm#471]
Setup: 
Typescript == 4.9.5
node == 20.0.0
theia == 1.45.0
Webpack == 5.90.3
parquet-wasm == 0.5.0
apache-arrow == 15.0.0

I tried the example code: 

```
const ipcStream = arrow.tableToIPC(rainfall, 'stream');
// the following line crashes
const wasmTable = parquetWASM.Table.fromIPCStream(ipcStream);
```

and get the error message _Cannot read properties of undefined (reading 'fromIPCStream')_. Inspecting the ipcStream at runtime reveals that ipcStream is an Uint8Array with 24400 entries. 

My imports: 

```
import * as arrow from 'apache-arrow';
import * as parquetWASM from 'parquet-wasm';
```

Do you have any idea of what is going wrong?

**Comment by kylebarron** [comment]
The API changed after 0.5.0. You can look at the 0.5.0 README for an example https://github.com/kylebarron/parquet-wasm/tree/v0.5.0?tab=readme-ov-file#example

**Comment by MaTiAtSIE** [comment]
Thanks for this hint (it is really good that you answer so fast to the issues 👍). Now I have another Problem with the writeParquet function. The following lines make trouble

```
const uintArr = tableToIPC(rainfall, 'stream');
const parquetBuffer = writeParquet(
  uintArr, // this should be a table
  writerProperties
);
```

as writeParquet is expecting a Table:

```
Argument of type 'Uint8Array' is not assignable to parameter of type 'Table'.
  Type 'Uint8Array' is missing the following properties from type 'Table': free, recordBatch, toFFI, intoFFI, and 3 more.
```

So I tried 

```
let writerProperties = new WriterPropertiesBuilder();
writerProperties = writerProperties.setCompression(Compression.ZSTD);
const props = writerProperties.build();
const uintArr = tableToIPC(rainfall, 'stream');
const arrTable = Table.fromIPCStream(uintArr);
const parquetBuffer = writeParquet(
    arrTable,
    props
);
```

and importing from 'parquet-wasm/node/arrow1' which compiles. However, this produces an empty schema. Therefore, the question is, how to call writeParquet from the return of tableToIPC(rainfall, 'stream')? 

BTW: I changed the apache-arrow version to 13.0.0 as this version is also used in parquet-wasm 0.5.0

**Comment by MaTiAtSIE** [comment]
Hello Kyle, thanks for your support and time :). Indeed, your code works, and it turned out that my code, [which I posted earlier](https://github.com/kylebarron/parquet-wasm/issues/471#issuecomment-1982897515), works as well. However, the schema is empty when I inspect the table by setting a break point after calling 'tableFromIPC(readParquet(parquetBuffer));'. 
![empty_schema](https://github.com/kylebarron/parquet-wasm/assets/144116299/6fc224b6-2e31-45b4-9a15-bfe5a931f272)

**Comment by kylebarron** [comment]
The entire table is empty. `readParquet` does not return a `Uint8Array`, it returns a `Table` object, so you need to call a method to convert that table to IPC bytes first. It should be something like `tableFromIPC(readParquet().intoIPCStream())`. The types will guide you

**Comment by kylebarron** [comment]
I think the right abstract is a class like `ParquetFile` from the pyarrow world in Python that only reads the metadata. We don't have something like that today, but it might come in in the next release
