### ISSUE TITLE
reading wbindgen issue with webpack

### ISSUE THREAD

**Issue by kbatchu** [kylebarron/parquet-wasm#486]
I am getting an error message "Uncaught TypeError TypeError: Cannot read properties of undefined (reading '__wbindgen_add_to_stack_pointer') at readParquet (c:\PROJECTS\DataVizSandbox\DuckDBWasm\node_modules\parquet-wasm\esm\parquet_wasm.js:300:1).

I am using webpack 5.89.0. I get this same error message with both "parquet-wasm "^0.6.0-beta.2" and '"@geoarrow/geoparquet-wasm": "^0.2.0-beta.2".

Any idea on how to fix this?

Thanks

**Comment by kylebarron** [comment]
> esm\parquet_wasm

You should usually be using the bundler entry point with webpack. 

I don't use webpack myself but there's an example template here: https://github.com/rustwasm/rust-webpack-template/blob/master/template/webpack.config.js

**Comment by kylebarron** [comment]
I made the existing text in the README bold: https://github.com/kylebarron/parquet-wasm/pull/487

**Comment by kbatchu** [comment]
I tried using - import * as Parquet from "parquet-wasm"; and Parquet.readParquet() but I am still getting the same error.

**Comment by kylebarron** [comment]
You're probably getting the esm import by default. In that case, you need to do
```js
await Parquet.default();
Parquet.readParquet()
```

**Comment by kylebarron** [comment]
I think this issue is resolved, but feel free to comment again if not
