### ISSUE TITLE
`free()` not work for `ParquetFile` and so on

### ISSUE THREAD

**Issue by simline** [kylebarron/parquet-wasm#524]
Nodejs v22
parquet-wasm 0.6

`global.gc()` and `xxx.free()` nither work: `process.memoryUsage()` won't decrease

**Comment by kylebarron** [comment]
This is expected. `free()` releases memory _within the WebAssembly memory space_. The WebAssembly memory space is its own ArrayBuffer, separate from the general JavaScript heap. You'd have to delete the entire `WebAssembly.Memory` object for the JS runtime to clean up that WebAssembly memory.
