### ISSUE TITLE
Large reads consistently fail with: "RuntimeError: unreachable"

### ISSUE THREAD

**Issue by Vectorrent** [kylebarron/parquet-wasm#577]
Node.js: v18.20.4
apache-arrow: ^16.1.0
arrow-js-ffi: ^0.4.2
parquet-wasm: ^0.6.1

Attempting to stream/load large Parquet files will cause `parquet-wasm` to crash with the following kinds of error:
```
[ryan@ryan-pc ode]$ node misc/parquet.js 
wasm://wasm/014f6eb2:1


RuntimeError: unreachable
    at wasm://wasm/014f6eb2:wasm-function[6685]:0x413b66
    at wasm://wasm/014f6eb2:wasm-function[128]:0xa99a7
    at wasm://wasm/014f6eb2:wasm-function[1965]:0x31864a
    at wasm://wasm/014f6eb2:wasm-function[5633]:0x3fe842
    at __wbg_adapter_50 (/home/ryan/repos/ode/node_modules/parquet-wasm/node/parquet_wasm.js:236:10)
    at real (/home/ryan/repos/ode/node_modules/parquet-wasm/node/parquet_wasm.js:221:20)
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.20.4
```
I have tested with both the sync and async APIs, as well as the new FFI method; they all fail with errors like this, when trying to load large Parquet files (~2GB). I'm guessing there might be some hard memory limits in Node/WASM, so I tried increasing `--max-old-space-size=8192`, but that didn't seem to work. Any help would be greatly appreciated!

Here is a concise reproducer, with 1 broken URL and 1 functional URL:
```js
import { Table } from 'apache-arrow'
import { parseRecordBatch } from 'arrow-js-ffi'
import { wasmMemory, readParquetStream } from 'parquet-wasm'

// Large, broken download
const url =
    'https://huggingface.co/datasets/HuggingFaceFW/fineweb/resolve/main/data/CC-MAIN-2024-18/001_00003.parquet'

// Small, successful download
// const url =
//     'https://huggingface.co/datasets/HuggingFaceFW/fineweb/resolve/main/data/CC-MAIN-2024-18/004_00018.parquet'

;(async () => {
    const stream = await readParquetStream(url)

    const batches = []
    for await (const wasmRecordBatch of stream) {
        const ffiRecordBatch = wasmRecordBatch.intoFFI()
        const recordBatch = parseRecordBatch(
            wasmMemory().buffer,
            ffiRecordBatch.arrayAddr(),
            ffiRecordBatch.schemaAddr()
        )
        batches.push(recordBatch)
    }

    const table = new Table(batches)

    console.log('successfully loaded table')
})()
```

**Comment by Vectorrent** [comment]
Thanks for the update, @H-Plus-Time! I can't say that I fully understand your suggestion, nor do I have the skills (or time) to refactor Fineweb at the moment. Nevertheless, [I opened an issue on their repo](https://huggingface.co/datasets/HuggingFaceFW/fineweb/discussions/48). I don't expect that JavaScript is a high priority for anyone at Huggingface, but at the very least - maybe this will spark them to consider wasm32 restrictions, when building datasets in the future!

**Comment by kylebarron** [comment]
There's almost never a reason to have only a single row group when writing a parquet file. There should be internal chunking, which allows reading parts of a larger file that you couldn't load entirely into memory

**Comment by kylebarron** [comment]
I think this is outside the purview of parquet-wasm, so I'll close this.
