### ISSUE TITLE
Issue loading wasm file in Vite production build

### ISSUE THREAD

**Issue by lm93547** [kylebarron/parquet-wasm#637]
Hi, library works great locally for rendering GeoParquet with DeckGL, but when I build and deploy using the vite build command, the library stops working with the error: `TypeError: Cannot read properties of undefined (reading '__wbindgen_add_to_stack_pointer')` which I think is the library being unable to load.

Config info: `vite.config.ts`

```
import {defineConfig} from "vite";
import react from "@vitejs/plugin-react";
import wasm from "vite-plugin-wasm";

export default defineConfig({
    plugins: [react(), wasm()],
    optimizeDeps: {
        exclude: [
            "@rollup/browser",
            "parquet-wasm",
            "@geoarrow/geoparquet-wasm",
        ],
    },
});
```

`tsconfig` (Something funky could be going on here with the way I am doing the module resolution?, or the target?)

```
{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,

    /* Bundler mode */
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",

    /* Linting */
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src"],
  "references": [{ "path": "./tsconfig.node.json" }]
}
```

Code to instantiate the library & load the GeoParquet file(s)
```
import wasmInit from "parquet_wasm";
import {tableFromIPC} from "apache-arrow";
import {readGeoParquet} from "@geoarrow/geoparquet-wasm";

const loadWasm = async () => {
    try {
        await wasmInit(); // Initialize with the ArrayBuffer
    } catch (error) {
        console.error("Error initializing wasm:", error);
    }
};

const fetchParquetFile = async (file = "/public/heb-poly.parquet") => {
    try {
        await loadWasm();
    } catch (error) {
        console.error("Error initializing wasm:", error);
    }
    const response = await fetch(file);
    const arrayBuffer = await response.arrayBuffer();
    return new Uint8Array(arrayBuffer);
};

const loadParquet = async (file = "/public/heb-poly.parquet") => {
    try {
        const parquetBytes = await fetchParquetFile(file);
        const arrowWasmTable = readGeoParquet(parquetBytes);
        const arrowTable = tableFromIPC(arrowWasmTable.intoIPCStream());
        return arrowTable;
    } catch (error) {
        console.error("Error loading parquet:", error);
    }
};

export {loadParquet};
```

 I have tried the following:
- Hosted the package in the `public` folder and tried importing from there: `import wasmInit from "../../public/js/pkg/parquet_wasm";` , same error seen. 
- Tried the wasm custom url, `index-DeJKP3ls.js:2268 Error initializing wasm: LinkError: WebAssembly.instantiate(): Import #4 "wbg" "__wbindgen_object_drop_ref": function import requires a callable`
- The wasm sync import: `Error initializing wasm: CompileError: WebAssembly.Module(): expected magic word 00 61 73 6d, found 3c 21 64 6f @+0` using the code: 
```
const loadWasm = async () => {
    const wasmFile = await fetch("../../public/js/pkg/parquet_wasm_bg.wasm");
    const wasmBuffer = await wasmFile.arrayBuffer();

    try {
        initSync(wasmBuffer);
    } catch (error) {
        console.error("Error initializing wasm:", error);
    }
};
```
 Any ideas greatly appreciated, & to note as well it does seem like the wasm files are loading when I check the network tabs, and the files exist in the built `dist` folder.
 Thanks

**Comment by kylebarron** [comment]
I've never used Vite in production with a wasm dependency, so I don't know the solution here, but I've seen issues pop up around using it with wasm.

I believe the core issue is that vite is mangling names in its build step. But you need to tell vite to not mangle these specific names that Rust's `wasm-bindgen` expects.

I assume if you tell vite to not minify it will work correctly. You might want to look at projects like https://github.com/nshen/vite-plugin-wasm-pack as well.

If you find a solution it would be great to post it here.

**Comment by kylebarron** [comment]
This isn't really a parquet-wasm or geoparquet-wasm problem; it's a general rust wasm-bindgen problem. I'm sure someone's come up with a solution before, we just have to surface it and document it. It looks like there's some similar discussion here: https://github.com/vitejs/vite/issues/4551
